spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rbacdemo?createDatabaseIfNotExist=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

mybatis:
  # model的包
  type-aliases-package: com.example.user.entity
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true